### ISSUE TITLE
Fix Responses in audit log

### ISSUE THREAD

**Issue by sishiihrg** [vistadataproject/rpcRouter#7]
Data is missing in audit log for some responses

{"name":"audit","hostname":"addgene-ubuntu-1604-vbox","pid":20224,"level":30,"clientAddress":"10.2.2.1:54538","rpcPacket":"[XWB]11302\u00010\u000bORQQAL LIST5000225f\u0004","transactionId":"6834e0b3-8fe5-4942-9b77-8629c6eb537a","msg":"RPC received; sending to VISTA","time":"2018-03-19T05:20:48.245Z","v":0},

{"name":"audit","hostname":"addgene-ubuntu-1604-vbox","pid":20224,"level":30,"clientAddress":"10.2.2.1:54538","vicsDataBuffer":{"type":"Buffer",**_"data":[]_**},"transactionId":"6834e0b3-8fe5-4942-9b77-8629c6eb537a","msg":"Sending response from VistA RPC Broker","time":"2018-03-19T05:20:48.246Z","v":0}, 

The response should read '^No Known Allergies' (router manger shows it)

**Comment by sishiihrg** [comment]
Change from bytes to strings

**Comment by mfuroyama** [comment]
Tracking in Jira: https://hawaiirg.atlassian.net/browse/VAM-612
